#!/bin/bash

if [ $1 = "help" ]
then
	echo "how to use the reader command"
	echo ""
	echo "reader <filename> runs the code <filename>"
	echo " - control-c to stop the code early will still shut off the reader"
	echo " - the serial port is determined automatically in the code, no"
	echo "   flags are required besides the filename"
	echo ""
	echo "potential problems:"
	echo " - the code that this runs must be in the /home/pi/Elara_Samples"
	echo "   gradle folder, using this command will always compile the "
	echo "   java code from that parent directory, regardless of where"
	echo "   this command is run from"
	echo " - the file name specified is case-sensitive and has to exist in"
	echo "   the app/src/main/java/Samples folder"
	echo " - the file name specified must not have an extension, for"
	echo "   example: running 'ConstantRead.java' means type "
	echo "   'reader ConstantRead'"


	exit 0
fi

tofile="plugins {
    id 'application'
}


repositories {
    flatDir {
        dirs '/home/pi/Elara_Samples/libs', '/usr/share/java'
    }

    mavenCentral()

}

dependencies {
    testImplementation 'junit:junit:4.13.2'

    implementation 'com.google.guava:guava:30.1-jre'

    implementation name: 'hid4java-develop-SNAPSHOT'
    implementation name: 'ltkjava-1.0.0.6'
    implementation name: 'org.json'
    implementation name: 'jSerialComm-2.2.0'
    implementation name: 'mercuryapi_nb'
    implementation name: 'purejavahidapi'

    implementation name: 'javafx-base-11'
    implementation name: 'javafx-controls-11'
    implementation name: 'javafx-fxml-11'
    implementation name: 'javafx-graphics-11'
    implementation name: 'javafx-media-11'
    implementation name: 'javafx-swing-11'
    implementation name: 'javafx-web-11'
}

application {
    mainClass = 'Samples.$1'
}"

echo -e  "$tofile" > /home/pi/Elara_Samples/app/build.gradle

bash /home/pi/Elara_Samples/gradlew run

echo "Stopping Reader"

stopfile="plugins {
    id 'application'
}


repositories {
    flatDir {
        dirs '/home/pi/Elara_Samples/libs', '/usr/share/java'
    }

    mavenCentral()

}

dependencies {
    testImplementation 'junit:junit:4.13.2'

    implementation 'com.google.guava:guava:30.1-jre'

    implementation name: 'hid4java-develop-SNAPSHOT'
    implementation name: 'ltkjava-1.0.0.6'
    implementation name: 'org.json'
    implementation name: 'jSerialComm-2.2.0'
    implementation name: 'mercuryapi_nb'
    implementation name: 'purejavahidapi'

    implementation name: 'javafx-base-11'
    implementation name: 'javafx-controls-11'
    implementation name: 'javafx-fxml-11'
    implementation name: 'javafx-graphics-11'
    implementation name: 'javafx-media-11'
    implementation name: 'javafx-swing-11'
    implementation name: 'javafx-web-11'
}

application {
    mainClass = 'Samples.StopRead'
}"

echo -e "$stopfile" > /home/pi/Elara_Samples/app/build.gradle

bash /home/pi/Elara_Samples/gradlew run
